"""
This code tries to decrypt an output generated by encrypt() of encrypt_for_decrypt_2.py.

Find and fix the bug(s)!

Author: Omer Rosenbaum
"""
SECRET = "12,Vswiw$evi$vih0$Zmspixw$evi$fpyi0$Epp$q}$fewi0$Evi$fipsrk$xs$}sy"


def decrypt(encrypted):
    (offset, encrypted_string) = encrypted.split(',')
    offset = (int(offset) - 4) // 2
    decrypted_string = ""
    for character in encrypted_string:
        decrypted_string += chr(ord(character) - offset)

    return decrypted_string


if __name__ == "__main__":
    print(decrypt(SECRET))
